# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eixo', models.CharField(max_length=45)),
            ],
        ),
    ]
