# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eixo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eixo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
